<?php
$z[0]=Array("global","",645,677);
$z[0][4]['name']="cfg_templets_skin";
$z[1]=Array("global","",777,809);
$z[1][4]['name']="cfg_templets_skin";
$z[2]=Array("global","",876,908);
$z[2][4]['name']="cfg_templets_skin";
$z[3]=Array("global","",1134,1166);
$z[3][4]['name']="cfg_templets_skin";
$z[4]=Array("global","",1231,1263);
$z[4][4]['name']="cfg_templets_skin";
$z[5]=Array("include","",1621,1658);
$z[5][4]['filename']="bt_nav.htm";
$z[6]=Array("global","",2798,2830);
$z[6][4]['name']="cfg_templets_skin";

?>